version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - node:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

volumes:
   node:
